app/routes/login.py
from flask import Flask, render_template, request, redirect, url_for, flash, Blueprint

from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, validators

from flask_sqlalchemy import SQLAlchemy

# create the extension
db = SQLAlchemy()
# create the app
app = Flask(__name__)
# configure the SQLite database, relative to the app instance folder
app.config["SQLALCHEMY_DATABASE_URI"] = "sqlite:///project.db"
# initialize the app with the extension
db.init_app(app)



# db = SQLAlchemy(app)  # Create SQLAlchemy instance with the Flask app directly

login_routes = Blueprint('login_routes', __name__)

@login_routes.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        user = User.query.filter_by(username=username).first()
        if user and user.password == password:
            flash('Login successful!', 'success')
            return redirect(url_for('home'))
        else:
            flash('Invalid username or password', 'danger')
    return render_template('login.html', form=form)

class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(50), unique=True, nullable=False)
    password = db.Column(db.String(100), nullable=False)

class LoginForm(FlaskForm):
    username = StringField('Username', validators=[validators.DataRequired()])
    password = PasswordField('Password', validators=[validators.DataRequired()])
    submit = SubmitField('Login')

@app.route('/')
def home():
    return "Welcome to the home page!"

if __name__ == '__main__':
    db.create_all()
    app.register_blueprint(login_routes)
    app.run(debug=True)

app/routes/register_admin.py
from flask import Flask, render_template, request, redirect, url_for, flash, Blueprint
from flask_mysqldb import MySQL

app = Flask(__name__)
app.secret_key = '1234567890'

register_admin_routes = Blueprint('register_admin_routes', __name__)
# MySQL configurations
app.config['MYSQL_HOST'] = 'localhost'
app.config['MYSQL_USER'] = 'root'
app.config['MYSQL_PASSWORD'] = 'rooot'
app.config['MYSQL_DB'] = 'oasc_db'

mysql = MySQL(app)

@register_admin_routes.route('/register_admin', methods=['GET'])
def index():
    return render_template('register_admin.html')

@register_admin_routes.route('/register_admin', methods=['GET','POST'])
def register():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        email = request.form['email']
        first_name = request.form['first_name']
        last_name = request.form['last_name']
        phone_number = request.form['phone_number']

        cur = mysql.connection.cursor()
        cur.execute("INSERT INTO users (username, password, email, first_name, last_name, phone_number) VALUES (%s, %s, %s, %s, %s, %s)", 
                    (username, password, email, first_name, last_name, phone_number))
        mysql.connection.commit()
        cur.close()

        flash('You have successfully registered', 'success')
        return redirect(url_for('admin_dashboard'))

    return render_template('register_admin.html')

if __name__ == '__main__':
    app.run(debug=True)

app/templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>About Us - Afan Oromo Spell Checker</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
</head>
<body>
    {% include 'navbar.html' %}
    <section class="hero">
        <div class="contain">
            <h1>About Us</h1>
            <p>We are a team of dedicated software engineering students from Haramaya University, passionate about linguistic diversity and technological innovation. Our project, the Afan Oromo Spell Checker, aims to address the challenges faced by writers and speakers of Afan Oromo in accurately communicating their thoughts and ideas.</p>
        </div>
    </section>

    <section class="team">
        <div class="contain">
            <h2>Meet Our Team</h2>
            <div class="team-members">
                <div class="team-member">
                    <img src="{{ url_for('static', filename='gal.jpg') }}" alt="Galata Wakwaya">
                    <h3>Galata Wakwaya</h3>
                    <p>Lead Developer</p>
                    
                </div>
                <div class="team-member">
                    <img src="{{ url_for('static', filename='170.jpg') }}" alt="Fufa Wakgari">
                    <h3>Fufa Wakgari</h3>
                    <p>Lead Developer</p>
                </div>
                <div class="team-member">
                    <img src="{{ url_for('static', filename='169.jpg') }}" alt="Lechisa Bedasa">
                    <h3>Lechisa Bedasa</h3>
                    <p>UI/UX Designer</p>
                </div>
                <div class="team-member">
                    <img src="{{ url_for('static', filename='el.jpg') }}" alt="Elias Bekele">
                    <h3>Elias Bekele</h3>
                    <p>UI/UX Designer</p>
                </div>
                
                <div class="team-member">
                    <img src="{{ url_for('static', filename='ku.jpg') }}" alt="Kumsa Kitesa">
                    <h3>Kumsa Kitesa</h3>
                    <p>UI/UX Designer</p>
                </div>
                <!-- Add more team members as needed -->
            </div>
        </div>
    </section>

    <section class="mission">
        <div class="contain">
            <h2>Our Mission</h2>
            <p>Our mission is to empower individuals and communities by providing a reliable and accessible tool for improving written communication in Afan Oromo. By leveraging our expertise in software development and linguistics, we strive to enhance the quality and accuracy of Afan Oromo text, thereby promoting literacy and preserving cultural heritage.</p>
        </div>
    </section>

    <section class="contact">
        <div class="contain">
            <h2>Contact Us</h2>
            <p>If you have any questions, suggestions, or feedback, please don't hesitate to reach out to us. We value your input and are committed to continually improving our project.</p>
            <p>Email: info@afanoromospellchecker.com</p>
            <p>Phone: +123 456 7890</p>
        </div>
    </section>

    
    {% include 'footer.html' %}
    <script src="{{ url_for('static', filename='scripts.js') }}"></script>
</body>
</html>

app/templates/admin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Dashboard</title>
    <style>
        .sidebar {
            width: 200px;
            background-color: #f1f1f1;
            padding: 20px;
            float: left;
        }
    </style>
</head>
<body>
    <div class="sidebar">
        <h2>Admin Panel</h2>
        <ul>
            <!-- <li><a href="/admin/user_management">User Management</a></li> -->
        </ul>
    </div>
    <div class="content" style="margin-left: 220px;">
        <h1>Welcome to Admin Dashboard</h1>
    </div>
</body>
</html>

app/templates/admin_dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
</head>
<body>
    <h1>Welcome</h1>
    <p><a href="{{ url_for('register_admin_routes.register_admin') }}">Register</a></p>
</body>
</html>

app/templates/contact.html
<link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
<body>
    {% include 'navbar.html' %}
    <main>
        <form action="submit_form.php" method="POST">
            <label for="name">Name:</label>
            <input type="text" id="name" name="name" required>
            
            <label for="email">Email:</label>
            <input type="email" id="email" name="email" required>
            
            <label for="message">Message:</label>
            <textarea id="message" name="message" required></textarea>
            
            <button type="submit">Submit</button>
        </form>
    </main>
    {% include 'footer.html' %}
    <script src="{{ url_for('static', filename='scripts.js') }}"></script>
</body>

app/templates/dictionary.html
<!-- templates/dictionary.html -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Spell Checker</title>
    <!-- Include Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>

<div class="container mt-5">
    <h2>Spell Checker</h2>
    <div class="row">
        <div class="col-md-6">
            <form id="spellCheckerForm">
                <div class="form-group">
                    <label for="wordInput">Root Word:</label>
                    <input type="text" class="form-control" id="wordInput" name="wordInput" required>
                </div>
                <div class="form-group">
                    <label for="classWord">Word Class:</label>
                    <select class="form-control" id="classWord" name="classWord">
                        <option value="Noun">Noun</option>
                        <option value="Verb">Verb</option>
                        <option value="Functional Word">Functional Word</option>
                    </select>
                </div>
                
                <button type="submit" class="btn btn-primary">Add Word</button>
            </form>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="existsModal" tabindex="-1" role="dialog" aria-labelledby="existsModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="existsModalLabel">Word Already Exists</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                The word with this class already exists in the dictionary.
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<!-- Include jQuery and Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

<script>
    $(document).ready(function(){
        $('#spellCheckerForm').submit(function(e){
            e.preventDefault();
            var rootWord = $('#wordInput').val();
            var classWord = $('#classWord').val();
            // Send the rootWord to Flask for processing
            $.ajax({
                url: '/add_to_dictionary',
                method: 'POST',
                contentType: 'application/json',
                data: JSON.stringify({rootWord: rootWord,classWord: classWord}),
                success: function(response){
                    if(response.exists){
                        $('#existsModal').modal('show');
                    } else {
                        // Do something if the word was successfully added
                        alert("Word added successfully!");
                    }
                }
            });
        });
    });
</script>

</body>
</html>

app/templates/footer.html
<html>
<style>
    @import url("https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;400;500;600;700;800;900&display=swap");

</style>
<link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
<body>
  <footer class="footer">
    <div class="waves">
      <div class="wave" id="wave1"></div>
      <div class="wave" id="wave2"></div>
      <div class="wave" id="wave3"></div>
      <div class="wave" id="wave4"></div>
    </div>
    <ul class="social-icon">
      <li class="social-icon__item"><a class="social-icon__link" href="https://www.facebook.com/">
          <ion-icon name="logo-facebook"></ion-icon>
        </a></li>
      <li class="social-icon__item"><a class="social-icon__link" href="https://twitter.com/">
          <ion-icon name="logo-twitter"></ion-icon>
        </a></li>
      <li class="social-icon__item"><a class="social-icon__link" href="www.linkedin.com/

        ">
          <ion-icon name="logo-linkedin"></ion-icon>
        </a></li>
      <li class="social-icon__item"><a class="social-icon__link" href="https://www.instagram.com/">
          <ion-icon name="logo-instagram"></ion-icon>
        </a></li>
    </ul>
    <ul class="menu">
      <li class="menu__item"><a class="menu__link" href="/">Home</a></li>
      <li class="menu__item"><a class="menu__link" href="/about">About</a></li>
      <li class="menu__item"><a class="menu__link" href="#">Services</a></li>
      <li class="menu__item"><a class="menu__link" href="/about">Team</a></li>
      <li class="menu__item"><a class="menu__link" href="/contact">Contact</a></li>

    </ul>
    <p>&copy;<span id="currentYear"></span> Afro Tech | All Rights Reserved</p>

  </footer>
  <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
  <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
</body>

</html>

app/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <title>Sirreessaa Qubeeffama Afaan Oromoo</title>
</head>

<body>
    {% include 'navbar.html' %}

 

    <!-- Suggestions container -->
    <div id="suggestions">
        <ul></ul>
        <div id="suggestion-actions">
            <i class="bi bi-slash-circle"></i>
            <i class="bi bi-file-earmark-plus"></i>
        </div>
    </div>



    <div class="container">
      
        <div id="inputText" class="text-area" contenteditable="true"  oninput="handleInput(event)" onpaste="handlePaste(event)"
        ondrop="handleDrop(event)" data-text="As irraa barreessuu jalqabi">
        
         
        </div>
        
        <div class="suggestions-container">
          <div class="suggestions-header">
            <span class="suggestions-logo"><img id="avatar" src="{{ url_for('static', filename='o.jpg') }}" alt=""></span> Qajeelfama
          </div>
          <div class="suggestions-content">
            <h2>Eegaluuf.</h2>
            <p><span>Sadarkaa 1:</span> Barreeffama kee itti dabali, Seerlugaan dhimmoota kamiyyuu jala sarara.</p>
            <p><span>Sadarkaa 2:</span> Yaada ilaaluuf sarara jala jiru irratti cuqaasi.</p>
            <p><span>Sadarkaa 3:</span> Yaada tokko cuqaasuun fudhadhu.</p>
        </div>
        
        </div>
      </div>
      
      {% include 'footer.html' %}
    <script src="{{ url_for('static', filename='scripts.js') }}"></script>
</body>

</html>

app/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='login_css.css') }}">
</head>
<body>
    <div class="container">
        <h1>Login Page</h1>
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        {% for message in messages %}
        <div class="message {{ message[1] }}">{{ message[0] }}</div>
        {% endfor %}
        {% endif %}
        {% endwith %}
        <form method="POST">
            {{ form.csrf_token }}
            <div>
                <label for="username">Username:</label>
                {{ form.username }}
            </div>
            <div>
                <label for="password">Password:</label>
                {{ form.password }}
            </div>
            <button type="submit">Login</button>
        </form>
    </div>
</body>
</html>

app/templates/navbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sirreessaa Qubeeffama Afaan Oromoo</title>
</head>
<body>
    <nav class="navbar">
        <ul class="navbar-nav">
            <li class="nav-item"><a href="/" class="nav-link">
                    <div id="avatar">
                        <img src="{{ url_for('static', filename='oda.jpg') }}" alt="Oda Oromo Icon">
                    </div>
                </a></li>
            <li class="nav-item">
                <div id="header-container">
                    <h1>Sirreessaa Qubeeffama Afaan Oromoo</h1>
                </div>
            </li>
            <li class="nav-item"><a href="/" class="nav-link">Home</a></li>
            <li class="nav-item"><a href="/about" class="nav-link">About</a></li>
            <li class="nav-item"><a href="/contact" class="nav-link">Contact</a></li>
        </ul>
        <div class="theme-toggle">
            <label class="switch">
                <input type="checkbox" id="theme-toggle-checkbox">
                <span class="slider round"></span>
            </label>
        </div>
    </nav>
</body>
</html>

app/templates/register_admin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Register</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='login_css.css') }}">

</head>
<body>
    <h1>Register</h1>
    {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
        {% for category, message in messages %}
          <div class="alert alert-{{ category }}">{{ message }}</div>
        {% endfor %}
      {% endif %}
    {% endwith %}
    <form method="POST" action="{{ url_for('register_admin_routes.index') }}">
        <label for="username">Username:</label>
        <input type="text" id="username" name="username" required><br>
        <label for="password">Password:</label>
        <input type="password" id="password" name="password" required><br>
        <label for="email">Email:</label>
        <input type="email" id="email" name="email" required><br>
        <label for="first_name">First Name:</label>
        <input type="text" id="first_name" name="first_name" required><br>
        <label for="last_name">Last Name:</label>
        <input type="text" id="last_name" name="last_name" required><br>
        <label for="phone_number">Phone Number:</label>
        <input type="text" id="phone_number" name="phone_number" required><br>
        <input type="submit" value="Register">
    </form>
</body>
</html>